version: '3'

services:
  web-app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/project
    command: >
        sh -c "python server/manage.py runserver 0.0.0.0:8080"

    environment:
      TZ: Europe/Moscow
