version: '3'

services:
  web-app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/project
    command: >
        sh -c "python server/manage.py runserver 0.0.0.0:8000"

    environment:
      TZ: Europe/Moscow